Resources:
  ExampleSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl : PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: udacityTestSiteBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ExampleSiteBucket
                - /*
      Bucket: !Ref ExampleSiteBucket
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - ExampleSiteBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - ExampleSiteBucket
          - DomainName
    Description: Name of S3 bucket to hold website content